"""add eda workflow execution tables

Revision ID: 9ba36d2688cf
Revises: 75334592c859
Create Date: 2026-01-08 15:02:25.314810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ba36d2688cf'
down_revision: Union[str, None] = '75334592c859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eda_workflow_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=False),
    sa.Column('workflow_type', sa.String(length=50), nullable=False),
    sa.Column('table_asset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('tasks_total', sa.Integer(), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('tasks_failed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('artifacts', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('data_structure_type', sa.String(length=50), nullable=True),
    sa.Column('column_type_inferences', sa.Text(), nullable=True),
    sa.Column('user_intent', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['table_asset_id'], ['table_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eda_workflow_executions_data_structure_type'), 'eda_workflow_executions', ['data_structure_type'], unique=False)
    op.create_index(op.f('ix_eda_workflow_executions_id'), 'eda_workflow_executions', ['id'], unique=False)
    op.create_index(op.f('ix_eda_workflow_executions_status'), 'eda_workflow_executions', ['status'], unique=False)
    op.create_index(op.f('ix_eda_workflow_executions_table_asset_id'), 'eda_workflow_executions', ['table_asset_id'], unique=False)
    op.create_index(op.f('ix_eda_workflow_executions_user_id'), 'eda_workflow_executions', ['user_id'], unique=False)
    op.create_index(op.f('ix_eda_workflow_executions_workflow_id'), 'eda_workflow_executions', ['workflow_id'], unique=True)
    op.create_index(op.f('ix_eda_workflow_executions_workflow_type'), 'eda_workflow_executions', ['workflow_type'], unique=False)
    op.create_table('eda_workflow_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_execution_id', sa.Integer(), nullable=False),
    sa.Column('log_level', sa.String(length=20), nullable=False),
    sa.Column('log_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['eda_workflow_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eda_workflow_logs_id'), 'eda_workflow_logs', ['id'], unique=False)
    op.create_index(op.f('ix_eda_workflow_logs_log_level'), 'eda_workflow_logs', ['log_level'], unique=False)
    op.create_index(op.f('ix_eda_workflow_logs_log_type'), 'eda_workflow_logs', ['log_type'], unique=False)
    op.create_index(op.f('ix_eda_workflow_logs_task_id'), 'eda_workflow_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_eda_workflow_logs_timestamp'), 'eda_workflow_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_eda_workflow_logs_tool_name'), 'eda_workflow_logs', ['tool_name'], unique=False)
    op.create_index(op.f('ix_eda_workflow_logs_workflow_execution_id'), 'eda_workflow_logs', ['workflow_execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eda_workflow_logs_workflow_execution_id'), table_name='eda_workflow_logs')
    op.drop_index(op.f('ix_eda_workflow_logs_tool_name'), table_name='eda_workflow_logs')
    op.drop_index(op.f('ix_eda_workflow_logs_timestamp'), table_name='eda_workflow_logs')
    op.drop_index(op.f('ix_eda_workflow_logs_task_id'), table_name='eda_workflow_logs')
    op.drop_index(op.f('ix_eda_workflow_logs_log_type'), table_name='eda_workflow_logs')
    op.drop_index(op.f('ix_eda_workflow_logs_log_level'), table_name='eda_workflow_logs')
    op.drop_index(op.f('ix_eda_workflow_logs_id'), table_name='eda_workflow_logs')
    op.drop_table('eda_workflow_logs')
    op.drop_index(op.f('ix_eda_workflow_executions_workflow_type'), table_name='eda_workflow_executions')
    op.drop_index(op.f('ix_eda_workflow_executions_workflow_id'), table_name='eda_workflow_executions')
    op.drop_index(op.f('ix_eda_workflow_executions_user_id'), table_name='eda_workflow_executions')
    op.drop_index(op.f('ix_eda_workflow_executions_table_asset_id'), table_name='eda_workflow_executions')
    op.drop_index(op.f('ix_eda_workflow_executions_status'), table_name='eda_workflow_executions')
    op.drop_index(op.f('ix_eda_workflow_executions_id'), table_name='eda_workflow_executions')
    op.drop_index(op.f('ix_eda_workflow_executions_data_structure_type'), table_name='eda_workflow_executions')
    op.drop_table('eda_workflow_executions')
    # ### end Alembic commands ###
