import { useState } from "react";
import { Sparkles, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Drawer,
  DrawerContent,
  DrawerHeader,
  DrawerTitle,
} from "@/components/ui/drawer";
import { useTableStore } from "@/store/tableStore";
import { useToast } from "@/hooks/use-toast";
import { useBreakpoint } from "@/hooks/useBreakpoint";
import { WorkspaceTab, Artifact } from "@/types";
import { generateRandomCharts } from "@/lib/chartUtils";
import {
  AIFloatingButton,
  AIActionButtons,
  AIOutputDisplay,
  AIChangelogPopover,
} from "./ai-panel";

interface AIActionsPanelProps {
  tableId: string;
  activeTab: WorkspaceTab;
  isOpen: boolean;
  onToggle: () => void;
}

const mockInsights = [
  {
    title: "Key Performance Analysis",
    bullets: [
      "Revenue shows consistent upward trend with 15% monthly growth",
      "Top 3 products account for 65% of total sales volume",
      "Customer acquisition cost decreased by 8% this quarter",
    ],
  },
];

const mockDoc = `# Sales Analytics Q4 Summary

## Key Findings
- Total Revenue: $335,842
- Top Product: Report Builder (312 units)

*Generated by AI*`;

type ActionType = "insights" | "charts" | "doc" | "explain";

const AIActionsPanel = ({ tableId, activeTab, isOpen, onToggle }: AIActionsPanelProps) => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [currentAction, setCurrentAction] = useState<ActionType | null>(null);
  const [output, setOutput] = useState<{ type: ActionType; content: any } | null>(null);
  const { addArtifact, selectedColumn, getChangelog } = useTableStore();
  const { toast } = useToast();
  const { isMobile } = useBreakpoint();
  const changelog = getChangelog(tableId);

  const simulateGeneration = async (action: ActionType, generator: () => any) => {
    setIsGenerating(true);
    setCurrentAction(action);
    setOutput(null);

    await new Promise((resolve) => setTimeout(resolve, 1500));

    const result = generator();
    setOutput({ type: action, content: result });
    setIsGenerating(false);
    setCurrentAction(null);
  };

  const handleGenerateInsights = () => {
    simulateGeneration("insights", () => mockInsights);
  };

  const handleRecommendCharts = () => {
    simulateGeneration("charts", () => generateRandomCharts(2 + Math.floor(Math.random() * 2)));
  };

  const handleGenerateDoc = () => {
    simulateGeneration("doc", () => mockDoc);
  };

  const handleExplainColumn = () => {
    if (!selectedColumn) return;
    simulateGeneration("explain", () => ({
      column: selectedColumn,
      explanation: `The "${selectedColumn}" column contains identifiers for record classification. It appears to be a primary key or foreign key reference used for data relationships.`,
    }));
  };

  const handleSaveInsight = (insight: { title: string; bullets: string[] }) => {
    const artifact: Artifact = {
      type: "insight",
      id: `ins-${Date.now()}`,
      tableId,
      content: {
        title: insight.title,
        summary: "AI-generated insights",
        bullets: insight.bullets,
        sourceColumns: [],
      },
      author: "AI Assistant",
      createdAt: new Date().toISOString(),
    };
    addArtifact(artifact);
    toast({ title: "Insight saved" });
  };

  const handleSaveChart = (chart: any) => {
    const artifact: Artifact = {
      type: "chart",
      id: `chart-${Date.now()}`,
      tableId,
      content: chart,
      createdAt: new Date().toISOString(),
    };
    addArtifact(artifact);
    toast({ title: "Chart saved" });
  };

  const handleSaveDoc = () => {
    if (output?.type !== "doc") return;
    const artifact: Artifact = {
      type: "doc",
      id: `doc-${Date.now()}`,
      tableId,
      content: { markdown: output.content, title: "AI Generated Documentation" },
      createdAt: new Date().toISOString(),
    };
    addArtifact(artifact);
    toast({ title: "Documentation saved" });
    setOutput(null);
  };

  // Panel content shared between drawer and sidebar
  const PanelContent = () => (
    <>
      <AIActionButtons
        isGenerating={isGenerating}
        currentAction={currentAction}
        selectedColumn={selectedColumn}
        onGenerateInsights={handleGenerateInsights}
        onRecommendCharts={handleRecommendCharts}
        onGenerateDoc={handleGenerateDoc}
        onExplainColumn={handleExplainColumn}
      />
      <div className="mt-4 flex-1 overflow-auto">
        <AIOutputDisplay
          isGenerating={isGenerating}
          output={output}
          onSaveInsight={handleSaveInsight}
          onSaveChart={handleSaveChart}
          onSaveDoc={handleSaveDoc}
        />
      </div>
    </>
  );

  // Mobile: Floating button + Bottom drawer
  if (isMobile) {
    return (
      <>
        {!isOpen && <AIFloatingButton onClick={onToggle} />}
        <Drawer open={isOpen} onOpenChange={(open) => !open && onToggle()}>
          <DrawerContent className="max-h-[85vh]">
            <DrawerHeader className="flex flex-row items-center justify-between pb-2">
              <div className="flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-primary" />
                <DrawerTitle>AI Actions</DrawerTitle>
              </div>
              <div className="flex items-center gap-1">
                <AIChangelogPopover changelog={changelog} />
                <Button variant="ghost" size="icon-sm" onClick={onToggle}>
                  <X className="w-4 h-4" />
                </Button>
              </div>
            </DrawerHeader>
            <div className="px-4 pb-6 overflow-auto flex-1">
              <PanelContent />
            </div>
          </DrawerContent>
        </Drawer>
      </>
    );
  }

  // Desktop: Floating button when closed, sidebar when open
  if (!isOpen) {
    return <AIFloatingButton onClick={onToggle} />;
  }

  return (
    <div className="w-72 flex-shrink-0 border-l border-border bg-card flex flex-col h-full overflow-hidden">
      {/* Header */}
      <div className="p-3 border-b border-border flex items-center justify-between flex-shrink-0">
        <div className="flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-primary" />
          <span className="text-sm font-medium">AI Actions</span>
        </div>
        <div className="flex items-center gap-1">
          <AIChangelogPopover changelog={changelog} />
          <Button variant="ghost" size="icon-sm" onClick={onToggle}>
            <X className="w-4 h-4" />
          </Button>
        </div>
      </div>

      {/* Actions */}
      <div className="p-3 border-b border-border flex-shrink-0">
        <AIActionButtons
          isGenerating={isGenerating}
          currentAction={currentAction}
          selectedColumn={selectedColumn}
          onGenerateInsights={handleGenerateInsights}
          onRecommendCharts={handleRecommendCharts}
          onGenerateDoc={handleGenerateDoc}
          onExplainColumn={handleExplainColumn}
        />
      </div>

      {/* Output */}
      <div className="flex-1 overflow-auto p-3 scrollbar-thin">
        <AIOutputDisplay
          isGenerating={isGenerating}
          output={output}
          onSaveInsight={handleSaveInsight}
          onSaveChart={handleSaveChart}
          onSaveDoc={handleSaveDoc}
        />
      </div>
    </div>
  );
};

export default AIActionsPanel;
